apiVersion: apps/v1
kind: Deployment
metadata:
  # NameSpace
  namespace: comningsoon
  name: deploy-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: nginx-name
        image: ahmed1399/testing:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8090